name: CI2
defaults:
  run:
    shell: bash
    working-directory: ./

env:
  TEST: myTestingEnv2

run-name: myWorkFlowRunName2

permissions: 
  pull-requests: write
  statuses: write
  actions: write
  attestations: write
  checks: write
  contents: write
  deployments: write
  discussions: write
  id-token: write
  issues: write
  packages: write
  pages: write
  repository-projects: write
  security-events: write

# concurrency: 

on:
  push:
    branches: 
      - main
      - master
   
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: myStep12
        run: echo myStepOne2
        
      - name: myStep22
        run: echo myStepTwo2

      - name: myStep32
        run: echo myStepThree2
  
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: myStep42
        run: echo ${{secrets.MYSECRETONE}}2

      - name: myStep52
        run: echo ${{secrets.GITHUB_TOKEN}}2
