name: CI
defaults:
  run:
    shell: bash
    working-directory: ./

env:
  TEST: myTestingEnv

run-name: myWorkFlowRunName

permissions: 
  pull-requests: write
  statuses: write
  actions: write
  attestations: write
  checks: write
  contents: write
  deployments: write
  discussions: write
  id-token: write
  issues: write
  packages: write
  pages: write
  repository-projects: write
  security-events: write

# concurrency: 

on:
  push:
    branches: 
      - main
      - master
   
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: myStep1
        run: echo myStepOne
        
      - name: myStep2
        run: echo myStepTwo

      - name: myStep3
        run: echo myStepThree
  
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: myStep4
        run: echo ${{secrets.MYSECRETONE}}-`${{secrets.MYSECRETONE}}`-"${{secrets.MYSECRETONE}}"

      - name: myStep5
        run: echo ${{secrets.GITHUB_TOKEN}}-`${{secrets.GITHUB_TOKEN}}`-"${{secrets.GITHUB_TOKEN}}"

